language: r
sudo: false
cache: packages
warnings_are_errors: true
use_bioc: true
bioc_required: true
cran: http://cran.rstudio.com
addons:
  apt:
    packages:
    - libfftw3-dev
    - libgsl0-dev
    - libgsl0ldbl
os:
- linux
- osx
osx_image: xcode9
dist: trusty
env:
  global:
  - RGL_USE_NULL=TRUE
  - PROJECT_NAME=neuroconductor
  - DISPLAY=:99.0
r_check_args: "--as-cran --install-args=--build"
before_install:
- ulimit -n 2048
- export PROJ_DIR=`basename $PWD`
- fname=travis_helpers.sh
- wget -O ${fname} http://bit.ly/travis_helpers
- cat ${fname}; source ${fname}; rm ${fname}
- cat DESCRIPTION
- start_xvfb ;
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then no_open_mp ; fi
- Rscript -e 'source("https://install-github.me/mangothecat/callr")'
- remove_neuroc_packages
- cat DESCRIPTION
- install_remotes_no_dep
- cat DESCRIPTION
- export PACKAGE_NAME=`package_name`
- if [[ "${PACKAGE_NAME}" == "waveslim" ]]; then fftw_install ; fi
- if [[ "${PACKAGE_NAME}" == "dti" ]]; then gsl_install ; fi
- if [[ "${PACKAGE_NAME}" == "ROpenCVLite" ]]; then shopt -s expand_aliases ; x=`Rscript
  -e "cat(Sys.which('R'))"` ; alias R="travis_wait 100 ${x}" ; fi
after_success:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
after_failure:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
before_deploy:
- if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then rm -f *.tar.gz; fi
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: "${PACKAGE_NAME}*.t*gz"
  on:
    tags: true
  api-key:
    secure: Sy8MOeLorZF4SpxXsSgfI5TBUBPtuuMGiocPJlMBrGZSM6l1IezUHAoaLOBggoaei6ZjChNSZtbyOobP/lXflEt+p6zb2pOO8CKehB6MtxEDd9m2QnCgGHFDvWgnGEScqduJzosgrsa35gg3v3cL+/RuprWcDyROLmODTjElEslzzOYJZ2d0f/63hcWMdGK6O5+ZSt9fufOjKpYYQ1Cl20OjUX29GWrqZ3p7DIK8gujmnakXWob2hyilGhIDeEYS/9DBnxCnrG6m0QQ48/zOIHHpz2eCMMVx+m8FR0bGb9gj8w7mCb7fmD9RJNWbp8H/O1XJ6HVJ5YArJw8l5fYyoQZMK3+dJArOIXpJRO9PHEAA1kTDjI5gJKzLsoT8JmIMrzEfaj6Y79FutiTnr+MZEozZfTuOFmdey5iGoNxhFCO+6WCVy+COf7aMMMBDDjyxX5z9FqZcFGP29/0Om32IsIQgeyhP2znbLDn8FGLiWGEgaVoiELP7yIyRK+zEu8tGxpttkYs2ODa3wUfhrjf76gEnUYuhkHPh+jkP769HJ4mUXdF4AyxwjtFjpDgq7pa7hgvyAVZ0ywwmSivc5kPYhb1QkB8y8FufCB7vhJfS7B9O3XNq9T7FRBMO1RsHe/Qd+cBRSqItHQPNElKeyVWqqzdHYrBS4uY0adv46h3fqGw=
after_deploy:
- if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then echo 'covr::coveralls(type = "all")'
  > neuroc_covr.R ; travis_wait 100 Rscript neuroc_covr.R ; rm neuroc_covr.R ; fi
