language: r
sudo: false
cache: packages
warnings_are_errors: true
use_bioc: true
bioc_required: true
cran: http://cran.rstudio.com
addons:
  apt:
    packages:
    - libfftw3-dev
    - libgsl0-dev
    - libgsl0ldbl
os:
- linux
- osx
osx_image: xcode9
dist: trusty
r:
- 3.2
- 3.3
- 3.4
- release
- devel
allow_failures:
- r: devel
- os: osx
env:
  global:
  - RGL_USE_NULL=TRUE
  - PROJECT_NAME=neuroconductor
  - DISPLAY=:99.0
r_check_args: "--as-cran --install-args=--build"
before_install:
- ulimit -n 2048
- export PROJ_DIR=`basename $PWD`
- fname=travis_helpers.sh
- wget -O ${fname} http://bit.ly/travis_helpers
- cat ${fname}; source ${fname}; rm ${fname}
- cat DESCRIPTION
- start_xvfb ;
- export rver=`r_version`;
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then no_open_mp ; fi
- Rscript -e 'source("https://install-github.me/mangothecat/callr")'
- jags_install
- remove_neuroc_packages
- cat DESCRIPTION
- install_remotes_no_dep
- cat DESCRIPTION
- export PACKAGE_NAME=`package_name`
- if [[ "${PACKAGE_NAME}" == "waveslim" ]]; then fftw_install ; fi
- if [[ "${PACKAGE_NAME}" == "dti" ]]; then gsl_install ; fi
- if [[ "${PACKAGE_NAME}" == "ROpenCVLite" || "${PACKAGE_NAME}" == "Rvision" ]]; then
  shopt -s expand_aliases ; x=`Rscript -e "cat(Sys.which('R'))"` ; alias R="travis_wait
  100 ${x}" ; fi
after_success:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
after_failure:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
before_deploy:
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then PKG_TARBALL=$(ls -1t *.tgz | head -n 1);
  PKG_TARBALL_WITH_R=`echo $PKG_TARBALL | sed 's/.tgz/_'"R${rver}"'.tgz/'` ; mv ${PKG_TARBALL}
  ${PKG_TARBALL_WITH_R} ; echo "Built tarball is ${PKG_TARBALL_WITH_R}" ; fi
- if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then rm -f *.tar.gz; fi
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: "${PACKAGE_NAME}*.t*gz"
  on:
    tags: true
  api-key:
    secure: WwaIr9f8p60r9wGmSwAgOAaUAr0cgYkKwk/n9oBbEEhx/AfbdyDHyqXzbTIcsSrb5IQ2no2OGO8rf6wm1wqMuDzidrlA9lEJkDqnWm5d8VsYYTKDN/6zuAxgFhjN37STo6+yZlKQ19BN8j1ADCO/yLKUUJm2fGEY6Po1bDtopp6GAgLbfCmZZR8PYoAkdP32pIeq6goD08rWGYfBN4E+D/AvzugNlFfgnEM3KeE42ZmZVorKzULUpfLMu3XwXBMpcsQOYtDrSCYgEAj49DhxIJj1haZwykKAC38C3JmQiqaT0UST4l4V832UGEc0A+jaOOtwm64fbMk/buB6A+Cn9gNsJgTM2BJXPLftcBDQdd6VFHX/RVKlyZqpJ4fzzbf21/WXWEn07f0dnoNa4ViKt5mgnj4LRHuA2E14dxd97171veF1Yc6ePGQ5Dg/RJpJbhTyNcjDZGGbq5B/5a6wS4HDP6jzJHe7a1g2iTJpC5BExdgMIaupyzYWH8TdQOi5UidICc/I5WQhW//Q+wrCeD98Oc7KacxCB7mS6EvvDb8IpTRD+7u9p7Vh6lANdCNAIKoHpEiiG9l1rhiidynrqkMwvQkhKR+MbZyNuvSsSBYjB+FSlGTWzFVZ3WRICs2QkePxgiuTt1nFMZTJtmEp5hEDQHKkybkqutCDIn0Wbmho=
after_deploy:
- if [[ "${TRAVIS_OS_NAME}" == "linux" && ${TRAVIS_R_VERSION_STRING} = "release" ]];
  then echo 'covr::coveralls(type = "all")' > neuroc_covr.R ; travis_wait 100 Rscript
  neuroc_covr.R ; rm neuroc_covr.R ; fi
